### ISSUE TITLE
Integration with nginx/docker setup

### ISSUE THREAD

**Issue by avidsapp** [mbrugger/letsencrypt-nginx-docker#2]
Will this integrate well with the automated jwilder/nginx-proxy?

**Comment by mbrugger** [comment]
I can't think of any reason why it should not work. But I will give it a try during the christmas holidays to find out :+1:

**Comment by avidsapp** [comment]
Any luck?

**Comment by mbrugger** [comment]
I did go through the documentation and it should be possible to add a Per-VIRTUAL_HOST configuration redirecting the authentication requests from letsencrypt
`location /.well-known/acme-challenge {
        root /tmp/letsencrypt/www;
}`

I use a different/simpler/less capable approach for configuring my reverse proxy by using http://nginx.org/en/docs/http/ngx_http_map_module.html to proxy requests to the correct docker container without duplicating the configuration. (https://github.com/mbrugger/letsencrypt-nginx-docker/blob/master/nginx-multiple-vhost.conf)

I am certain it will also work with jwilder/nginx-proxy

**Comment by BenHall** [comment]
I really like your approach and I've given this some thought. The biggest problem I see is how to execute the letsencrypt container.

1) You need to know the IP addresses / hostname in advance for the route to work. Using Docker Network in 1.9 or Weave might help but it's a dependency.
2) It needs to share the same directory, mounting both to a common directory would work.

One integration is to use nginx proxy as a base image and extend it with letsencrypt and a custom tmpl. It's the approach taken by https://github.com/dmp1ce/nginx-proxy-letsencrypt but it's still not ideal IMHO, I couldn't get it to work and hit the rate limit trying.

**Comment by mbrugger** [comment]
You can always use the staging server without the the rate limit for development/testing using 
`--server https://acme-staging.api.letsencrypt.org/directory`

I am not yet sure if I really like the shared volume approach. Therefore I [fixed the previous attempt](https://github.com/mbrugger/letsencrypt-nginx-docker/tree/master/standalone) using the standalone client and reverse proxy forwarding the request to the le docker container by adding the missing parameter `--standalone-supported-challenges http-01` to define http to be used for making the authentication request

I think most people will have a custom proxy/nginx configuration anyways so adding letsencrypt should interfere as little as possible with the existing configuration.

**Comment by avidsapp** [comment]
@BenHall - I ran into some issues with [dmp1ce/nginx-proxy-letsencrypt](https://github.com/dmp1ce/nginx-proxy-letsencrypt) as well, but have since got it working correctly ([see #25](https://github.com/dmp1ce/nginx-proxy-letsencrypt/issues/25)).

I like the @mbrugger approach too, but don't know enough to implement it myself. If there is substantial reason to use it over the shared volume approach I may look into switching.

I looked at [kid-nginx-letsencrypt-proxy](https://github.com/kid/nginx-letsencrypt-proxy) as well, but also had issues.
